config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :links do
	  member do
	    put "like", to: "links#upvote"
	    put "dislike", to: "links#downvote"
		end
	resources :comments
	end
  root 'links#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  	validates :user_id, :body , presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	acts_as_votable
	validates :url, :format => URI::regexp(%w(http https))
	validates :title , :user_id , presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  	validates :name , presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]
  before_action :logged_user
  before_action :right_user, only: [:destroy]
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
    def logged_user
      redirect_to new_user_session_path unless current_user
    end
    def right_user
      redirect_to :back if current_user != @comment.user
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :right_user, only: [:destroy, :edit, :update]
  before_filter :authenticate_user!, except: [:index,:show]
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end
  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
    def right_user
      redirect_to :back if current_user != @link.user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do%>
	<div class="comment_wrapper clearfix comment">
		<div class="pull-left">
			<p class="lead"><%=comment.body%></p>
			<p>
			<small>Submitted: <strong><%= time_ago_in_words(comment.created_at)%> ago</strong> By <%=comment.user.name%>
			</small> 
		</p>
		</div>
	<div class="btn-group pull-right">
		<%if comment.user == current_user%>
			<%= link_to "Edit" , edit_comment_path(comment), class: "btn btn-sm btn-default"%>
			<%= link_to "Delete" , comment , method: :delete , data: {confirm: "Are You Sure  ?"}, class: "btn btn-sm btn-default"%>
		<%end%>
	</div>
</div>
<%end%>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Reddit" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div id="logo" class="navbar-brand">
          <%=link_to "Reddit" ,root_path%>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right  ">
              <li><%= link_to "Submit Link" , new_link_path %></li>
              <li><%= link_to "Account", edit_user_registration_path%></li>
              <li><%= link_to "Sign Out", destroy_user_session_path , method: :delete%></li>
            </ul>
            <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Sign up" , new_user_registration_path%></li>
              <li><%= link_to "Sign In", new_user_session_path%></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div  id="container" class="col-lg-9 center-block">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; HassanTC 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title,class: "form-control" ,placeholder: "Type a title that descripes your link" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url,class: "form-control" , placeholder: "Type a linke eg https://hassantc.com" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title , link%> <br />
      <small class="author">
        Submitted: <%=time_ago_in_words(link.created_at)%>by <%= link.user.name%>
      </small>
    </h2>
  <div class="btn-group">
  	<a href="<%= link.url %>" class="btn btn-default btn-sm"> Visit URL</a>
  	<%= link_to like_link_path(link) , method: :put ,class: "btn btn-default btn-sm" do%>
  	<span class="glyphicon glyphicon-chevron-up"></span>
  	Upvote
  	<%=link.get_upvotes.size%>
  	<%end%>
 <%= link_to dislike_link_path(link) , method: :put ,class: "btn btn-default btn-sm" do%>
  	<span class="glyphicon glyphicon-chevron-down"></span>
  	Downvote
  	<%=link.get_downvotes.size%>
  	<%end%>
  </div>
</div>
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="page-header">
	<h1> <a href="<%= @link.url %>"><%=@link.title%></a><br><small>Submitted by: <%=@link.user.name%></small></h1>
</div>
<div class="btn-group">
	<%= link_to "Visit URL" , @link.url , class: "btn btn-primary"%>
</div>
<%if @link.user == current_user%>
	<div class="btn-group">
		<%=link_to "Edit" , edit_link_path(@link) , class: "btn btn-default"%>
		<%=link_to "Delete", @link , method: :delete , data: {confirm: "Are You Sure ?"}, class: "btn btn-default" %>
	</div>
<%end%>
<div class="btn-group pull-right">
<a href="<%= @link.url %>" class="btn btn-default btn-sm"> Visit URL</a>
  	<%= link_to like_link_path(@link) , method: :put ,class: "btn btn-default btn-sm" do%>
  	<span class="glyphicon glyphicon-chevron-up"></span>
  	Upvote
  	<%=@link.get_upvotes.size%>
  	<%end%>
 <%= link_to dislike_link_path(@link) , method: :put ,class: "btn btn-default btn-sm" do%>
  	<span class="glyphicon glyphicon-chevron-down"></span>
  	Downvote
  	<%=@link.get_downvotes.size%>
  	<%end%>
</div>
<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>
<div id="comments">
  <%= render :partial => @link.comments %>
</div>
  <%= form_for [@link , Comment.new] do |f|%>
    <div class="form-group">
      <%= f.text_field :body , as: :text ,class: "form-control" , row: "5"%>
    </div>
    <br>
    <%= f.submit "Add Comment" , class: "btn btn-primary"%>
  <%end%>